# Generated by Django 3.1.7 on 2021-03-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210326_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='roll',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='section',
            new_name='toppies',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='name',
            new_name='types',
        ),
    ]
