# Generated by Django 3.1.7 on 2021-03-26 14:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210326_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppies',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Regular'), ('item_key2', 'Square')], max_length=19),
        ),
    ]
