# Generated by Django 3.1.7 on 2021-03-26 16:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210326_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='types',
        ),
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], default='', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='pizza',
            name='roll',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='section',
            field=models.CharField(default='', max_length=100),
        ),
    ]
