# Generated by Django 3.1.7 on 2021-03-26 17:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210326_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='section',
        ),
        migrations.AddField(
            model_name='pizza',
            name='Size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Small', 'Small'), ('Mediam', 'Mediam'), ('Large', 'Large')], default='', max_length=18),
        ),
        migrations.AddField(
            model_name='pizza',
            name='Toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Onion', 'Onion'), ('Tomato', 'Tomato'), ('Corn', 'Corn'), ('Capsicum', 'Capsicum'), ('Cheese', 'Cheese'), ('Jalapeno', 'Jalapeno')], default='', max_length=42),
        ),
        migrations.AddField(
            model_name='pizza',
            name='Types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Regular', 'Regular'), ('Square', 'Square')], default='', max_length=10),
        ),
    ]
